# Dockerfile.client
FROM node:20
WORKDIR /app
COPY /app/package.json ./
RUN npm install -legacy-peer-deps
COPY ./app ./
RUN npm run build --verbose
EXPOSE 3000
ENV NEXT_PUBLIC_BACKEND_URL=http://flask:5001
CMD ["npm", "start", "-H", "0.0.0.0"]