version: "3"
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://flask-app:5001

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 5001:5001
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
